name: PocketMesh
options:
  bundleIdPrefix: com.pocketmesh
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    DEVELOPMENT_TEAM: ""

packages:
  MeshCore:
    path: MeshCore
  PocketMeshServices:
    path: PocketMeshServices

targets:
  PocketMesh:
    type: application
    platform: iOS
    sources:
      - path: PocketMesh
        excludes:
          - "**/*.md"
      - path: AppIcon.icon
    dependencies:
      - package: PocketMeshServices
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 0.2.1
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: apple-generic
        TARGETED_DEVICE_FAMILY: "1,2"
        UIBackgroundModes:
          - bluetooth-central
        NSBluetoothAlwaysUsageDescription: "PocketMesh uses Bluetooth to maintain connections with MeshCore radios, even in the background, so you can send and receive messages without opening the app."
        NSBluetoothPeripheralUsageDescription: "PocketMesh uses Bluetooth to connect to MeshCore radios."
        NSLocationWhenInUseUsageDescription: "PocketMesh can share your location with contacts on the mesh network."
        NSAccessorySetupKitSupports:
          - Bluetooth
        NSAccessorySetupBluetoothServices:
          - "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
        NSAccessorySetupBluetoothNames:
          - "MeshCore-"
      configs:
        Debug:
          INFOPLIST_FILE: PocketMesh/Info-Debug.plist
          PRODUCT_BUNDLE_IDENTIFIER: io.pocketmesh.app.debug
        Release:
          INFOPLIST_FILE: PocketMesh/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: io.pocketmesh.app

  PocketMeshTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PocketMeshTests
    dependencies:
      - target: PocketMesh
    settings:
      base:
        INFOPLIST_FILE: PocketMeshTests/Info.plist
        MARKETING_VERSION: 0.2.1
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: apple-generic
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PocketMesh.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PocketMesh"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  PocketMesh:
    build:
      targets:
        PocketMesh: all
        PocketMeshTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PocketMeshTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
